spring:
  datasource:
    password: root
    url : jdbc:mysql://localhost:3306/server
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true